package com.mna.springbootsecurity.payment.domain.entity;


import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Represents a payment transaction in the system.
 * This entity will be mapped to a "payment_transaction" table in the database.
 */
@Entity
@Table(name = "PAYMENT_TRANSACTION")
@Getter
@Setter
@ToString // Lombok: useful for logging
public class PaymentTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-incremented ID
    private Long id;

    @Column(nullable = false, unique = true) // Each order should be unique
    private String orderId; // ID generated by the payment gateway for the order/intent

    @Column(unique = true) // Payment ID from gateway, can be null initially
    private String paymentId; // ID generated by the payment gateway upon successful payment

    @Column(nullable = false)
    private BigDecimal amount;

    @Column(nullable = false, length = 3) // e.g., "INR", "USD"
    private String currency;

    @Column(nullable = false, length = 20) // e.g., CREATED, PENDING, SUCCESS, FAILED, REFUNDED
    private String status;

    @Column(nullable = false, length = 20) // e.g., RAZORPAY, STRIPE
    private String gateway;

    @Column(length = 255) // For any error messages or additional details
    private String details;

    @CreationTimestamp // Automatically set on creation
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp // Automatically set on update
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    // Standard equals and hashCode for JPA entities
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PaymentTransaction that = (PaymentTransaction) o;
        return Objects.equals(id, that.id) && Objects.equals(orderId, that.orderId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, orderId);
    }
}